
SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00033
  WEIGHT_DECAY: 0.00000
  IMS_PER_BATCH: 1
  START_ITERS: 2000
  END_ITERS: 50000
  LR_SCALE: 0.09
  WARMUP_ITERS: 1000

  MAX_EPOCHS: 300
  CHECKPOINT_PERIOD: 2
  LOG_PERIOD: 20
  BUNCH: 3000
  COARSE_STAGE: 0

INPUT:
  SIZE_TRAIN: [800,600]
  SIZE_TEST: [600,400]

DATASETS:
  TRAIN: "/data/wmy/NR/dataset/sport_1_small"
  NUM_FRAME: 1
  SHIFT: 0.0
  MAXRATION: 0.0
  ROTATION: 0.0
  
  USE_MASK: False

MODEL:
  COARSE_RAY_SAMPLING: 64
  FINE_RAY_SAMPLING: 64
  SAMPLE_METHOD: "NEAR_FAR"       #  "NEAR_FAR"     "BBOX" 

TEST:
  IMS_PER_BATCH: 1

OUTPUT_DIR: "/data/wmy/NR/RF_training/sport1_near_far"
