
SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.0003
  WEIGHT_DECAY: 0.000001
  IMS_PER_BATCH: 1
  START_ITERS: 2000
  END_ITERS: 50000
  LR_SCALE: 0.09
  WARMUP_ITERS: 1000

  MAX_EPOCHS: 100
  CHECKPOINT_PERIOD: 3000
  LOG_PERIOD: 30
  BUNCH: 3000
  COARSE_STAGE: 2

INPUT:
  SIZE_TRAIN: [800,600]
  SIZE_TEST: [600,400]

DATASETS:
  #TRAIN: "/data/wmy/NR/dataset/sport_1_small"
  TRAIN: "/data/public/share/xzq_dataset_new"
  NUM_FRAME: 1
  SHIFT: 0.0
  MAXRATION: 0.0
  ROTATION: 0.0
  
  USE_MASK: False

MODEL:
  COARSE_RAY_SAMPLING: 64
  FINE_RAY_SAMPLING: 64
  SAMPLE_METHOD: "BBOX"       #  "NEAR_FAR"     "BBOX" 
  BOARDER_WEIGHT: 1e10
  SAME_SPACENET: True

TEST:
  IMS_PER_BATCH: 1

OUTPUT_DIR: "/data/wmy/NR/RF_training/xzq_bbox_single"
